package com.example.taskmanager.model;

import jakarta.persistence.*;
import lombok.*;

//Entity representing task category grouping.
@Entity
@Table(name = "categories")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category {

    // Unique Id - generated by postgreSQL
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Category name must be unique
    @Column(nullable = false, unique = true)
    private String name;

    // Optional description for category
    private String description;
}
