package com.example.taskmanager.model;

import jakarta.persistence.*;
import lombok.*;

//Entity representing task priority level.
@Entity
@Table(name = "priorities")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Priority {

    // Primary key — auto generated by PostgreSQL
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //Priority label — LOW / MEDIUM / HIGH / URGENT
    @Column(nullable = false, unique = true)
    private String name;

    //Numeric ranking value for sorting
    @Column(nullable = false)
    private Integer level;
}
