package com.example.taskmanager.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Core entity representing a Task.
 * Contains relationships to User, Category, and Priority.
 */
@Entity
@Table(name = "tasks")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Task {

    // Primary key — auto generated by PostgreSQL
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //Short title of the task
    @Column(nullable = false)
    private String title;

    //Detailed description
    @Column(columnDefinition = "TEXT")
    private String description;

    //Task lifecycle status stored as STRING enum
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TaskStatus status;

    //Optional due date
    private LocalDate dueDate;

    //Many tasks belong to one user
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    //Many tasks belong to one category
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    //Many tasks belong to one priority
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "priority_id", nullable = false)
    private Priority priority;

    //Audit fields
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
