package com.example.taskmanager.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

//Entity representing application user who owns tasks.
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    // Primary key — auto generated by PostgreSQL
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Full name of the user
    @Column(nullable = false)
    private String name;

    //Email should be unique across users
    @Column(nullable = false, unique = true)
    private String email;

    //Timestamp when user record created
    @Column(name = "created_at")
    private LocalDateTime createdAt;
}
